### ISSUE TITLE
Create history collection per player to achive pure highest throw computation

### ISSUE THREAD

**Issue by rbalazs** [rbalazs/fylingdarts#1]

**Comment by rbalazs** [comment]
every palyer should have a collection of every valid 3 dart throw, so computing avg shall be trivial

**Comment by richercs** [comment]
This feature has been implemented:
    this.turnScore = function (currentPlayer) {
        var countDarts = _this.thrown() + 1;
        var turnThrows = currentPlayer.history.slice(-countDarts);
        var turnSum = 0;
        for (var i = 0; i < countDarts; i++) {
            turnSum += turnThrows[i];
        }
        currentPlayer.turnHistory.push(turnSum);
    };
